default_platform(:ios)

platform :ios do

  # Public lanes
  
#  desc "Runs linter"
#  lane :lint do
#    swiftlint
#    notification(message: "lint finished successfully")
#  end

#  desc "Runs tests"
#  lane :test do
#    swiftlint
#    scan(workspace: "Rogue-iOS.xcworkspace", devices: ["iPhone 11 Pro"], scheme: "Rogue-iOS")
#    notification(message: "test finished successfully")
#  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    test_flight_beta(configuration: "Release")
    notification(message: "TestFlight build (Release) finished successfully")
  end

  desc "Push a new staging build to TestFlight"
  lane :staging do
    test_flight_beta(configuration: "Staging")
    notification(message: "TestFlight build (Staging) finished successfully")
  end

  desc "Push a new build ready for App Store release"
  lane :release do
    precheck
    test_flight_beta(configuration: "Release")
    notification(message: "App Store build (Release) finished successfully")
  end

  # Private lanes

  private_lane :test_flight_beta do |options|
    configuration = options[:configuration]
 #   swiftlint
#    scan(workspace: "Rogue-iOS.xcworkspace", devices: ["iPhone 11 Pro"], scheme: "RogueClient")
    increment_build_number(xcodeproj: "Rogue-iOS.xcodeproj")
    build_app(workspace: "Rogue-iOS.xcworkspace", configuration: configuration, scheme: "RogueClient")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

end
